<?php
if (!function_exists('admin_h')) { function admin_h($v): string { return htmlspecialchars((string)($v??''), ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8',false); } }
$list=$list??['items'=>[],'ok'=>false,'q'=>''];$options=$options??['persons'=>[],'positions'=>[]];$message=$_SESSION['admin_flash_message']??null;$error=$_SESSION['admin_flash_error']??null;unset($_SESSION['admin_flash_message'],$_SESSION['admin_flash_error']);
$kindLabels=['permanent'=>'دائم','temporary'=>'موقت','acting'=>'سرپرستی','delegated'=>'تفویضی'];
ob_start();?>
<nav class="admin-breadcrumb"><a href="/admin/dashboard">داشبورد</a><span>/</span><a href="/admin/modules/organization">ساختار سازمانی</a><span>/</span><span>انتصاب‌ها</span></nav>
<section class="admin-module-hub admin-module-hub--teal"><div><h2>پست و انتصاب</h2><p>اتصال اشخاص به جایگاه سازمانی با حفظ سوابق</p></div><a class="admin-button admin-button--soft" href="/admin/organization-chart">مشاهده چارت</a></section>
<?php if($message):?><div class="admin-alert admin-alert--success"><?=admin_h($message)?></div><?php endif;?><?php if($error):?><div class="admin-alert"><?=admin_h($error)?></div><?php endif;?>
<section class="admin-section"><h3>ثبت انتصاب جدید</h3><form method="post" action="/admin/appointments" class="admin-form-grid"><input type="hidden" name="_token" value="<?=admin_h((new \IPKF\Security\Csrf())->token())?>">
<label>شخص<select name="person_reference" required><option value="">انتخاب شخص</option><?php foreach($options['persons'] as $x):?><option value="<?=admin_h($x['public_reference'])?>"><?=admin_h($x['title'])?></option><?php endforeach;?></select></label>
<label>پست سازمانی<select name="position_reference" required><option value="">انتخاب پست</option><?php foreach($options['positions'] as $x):?><option value="<?=admin_h($x['public_reference'])?>"><?=admin_h($x['organization_title'].' / '.($x['unit_title']?:'ستاد').' / '.$x['title'])?></option><?php endforeach;?></select></label>
<label>نوع انتصاب<select name="appointment_kind"><?php foreach($kindLabels as $k=>$v):?><option value="<?=$k?>"><?=$v?></option><?php endforeach;?></select></label>
<label>تاریخ شروع<input type="date" name="valid_from"></label><label>تاریخ پایان<input type="date" name="valid_to"></label>
<label class="admin-checkbox"><input type="checkbox" name="is_primary" value="1"> جایگاه اصلی شخص</label>
<label>شماره/مرجع حکم<input name="appointment_reference" maxlength="150"></label><label class="admin-form-grid__wide">توضیحات<textarea name="description" rows="3" maxlength="2000"></textarea></label>
<div class="admin-form-grid__wide"><button class="admin-button" type="submit">ثبت انتصاب</button></div></form></section>
<section class="admin-section"><form method="get" class="admin-users-search"><label>جستجو</label><div class="admin-users-search__row"><input name="q" value="<?=admin_h($list['q'])?>" placeholder="نام شخص، سازمان، واحد یا پست"><button class="admin-button">جستجو</button></div></form>
<?php if(!$list['ok']):?><div class="admin-alert">دریافت انتصاب‌ها ممکن نیست.</div><?php elseif(!$list['items']):?><div class="admin-empty-state">انتصابی ثبت نشده است.</div><?php else:?><div class="admin-users-table-wrap"><table class="admin-table"><thead><tr><th>شخص</th><th>سازمان/واحد</th><th>پست</th><th>نوع</th><th>بازه اعتبار</th><th>وضعیت</th></tr></thead><tbody><?php foreach($list['items'] as $a):?><tr><td><strong><?=admin_h($a['person_name'])?></strong><?php if($a['is_primary']):?><br><span class="admin-status-badge admin-status-badge--active">اصلی</span><?php endif;?></td><td><?=admin_h($a['organization_title'])?><br><small><?=admin_h($a['unit_title']?:'ستاد')?></small></td><td><?=admin_h($a['position_title'])?></td><td><?=admin_h($kindLabels[$a['appointment_kind']]??$a['appointment_kind'])?></td><td dir="ltr"><?=admin_h(($a['valid_from']?:'—').' تا '.($a['valid_to']?:'—'))?></td><td><?=admin_h($a['status'])?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<style>.admin-form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.admin-form-grid label{display:flex;flex-direction:column;gap:6px}.admin-form-grid__wide{grid-column:1/-1}.admin-checkbox{flex-direction:row!important;align-items:center;margin-top:26px}@media(max-width:700px){.admin-form-grid{grid-template-columns:1fr}}</style>
<?php $content=ob_get_clean();require __DIR__.'/layout.php';
