<?php
if (!function_exists('admin_h')) { function admin_h($v): string { return htmlspecialchars((string)($v??''),ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8',false); } }
$workspace=$workspace??['ok'=>false,'organizations'=>[],'units'=>[],'organization_positions'=>[],'users'=>[],'persons'=>[]];
$message=$_SESSION['admin_flash_message']??null;$error=$_SESSION['admin_flash_error']??null;
$activeTab=$_SESSION['admin_organization_setup_tab']??'organization';
unset($_SESSION['admin_flash_message'],$_SESSION['admin_flash_error'],$_SESSION['admin_organization_setup_tab']);
$allowedTabs=['organization','unit','position','identity','summary'];if(!in_array($activeTab,$allowedTabs,true)){$activeTab='organization';}
$token=admin_h((new \IPKF\Security\Csrf())->token());ob_start();?>
<nav class="admin-breadcrumb"><a href="/admin/dashboard">داشبورد</a><span>/</span><a href="/admin/modules/organization">ساختار سازمانی</a><span>/</span><span>راه‌اندازی ساختار</span></nav>
<section class="admin-module-hub admin-module-hub--teal"><div><h2>راه‌اندازی ساختار سازمانی</h2><p>هر بخش را در تب مستقل تکمیل کنید؛ پس از ثبت، همان تب فعال می‌ماند.</p></div><a class="admin-button admin-button--soft" href="/admin/organization-chart">مشاهده چارت</a></section>
<?php if($message):?><div class="admin-alert admin-alert--success" role="status"><?=admin_h($message)?></div><?php endif;?>
<?php if($error):?><div class="admin-alert admin-alert--danger" role="alert"><?=admin_h($error)?></div><?php endif;?>
<?php if(!$workspace['ok']):?><div class="admin-alert admin-alert--danger">دریافت اطلاعات پایه سازمانی ممکن نیست.</div><?php else:?>
<section class="admin-section admin-tab-workspace" data-active-tab="<?=admin_h($activeTab)?>">
<div class="admin-setup-tabs" role="tablist" aria-label="بخش‌های راه‌اندازی ساختار سازمانی">
<button type="button" class="admin-setup-tab" data-tab="organization" role="tab">سازمان</button>
<button type="button" class="admin-setup-tab" data-tab="unit" role="tab">واحد سازمانی</button>
<button type="button" class="admin-setup-tab" data-tab="position" role="tab">پست سازمانی</button>
<button type="button" class="admin-setup-tab" data-tab="identity" role="tab">اتصال کاربر به شخص</button>
<button type="button" class="admin-setup-tab" data-tab="summary" role="tab">خلاصه و اقدامات</button>
</div>

<div class="admin-setup-panel" data-panel="organization" role="tabpanel">
<div class="admin-panel-heading"><div><h3>ثبت سازمان</h3><p>سازمان اصلی یا زیرمجموعه را تعریف کنید.</p></div></div>
<form method="post" action="/admin/organization-setup" class="admin-form-stack admin-form-grid"><input type="hidden" name="_token" value="<?=$token?>"><input type="hidden" name="action" value="create_organization">
<label>عنوان فارسی<input name="title_fa" required maxlength="255"></label><label>عنوان انگلیسی<input name="title_en" dir="ltr" maxlength="255"></label><label>عنوان کوتاه<input name="short_title" maxlength="150"></label>
<label>سازمان بالادست<select name="parent_reference"><option value="">بدون بالادست</option><?php foreach($workspace['organizations'] as $o):?><option value="<?=admin_h($o['public_reference'])?>"><?=admin_h($o['display_path']??(str_repeat('— ',(int)$o['depth']).$o['title']))?></option><?php endforeach;?></select></label><label>ترتیب<input type="number" name="sort_order" min="0" value="0"></label><div class="admin-form-actions"><button class="admin-button">ثبت سازمان</button></div></form></div>

<div class="admin-setup-panel" data-panel="unit" role="tabpanel">
<div class="admin-panel-heading"><div><h3>ثبت واحد سازمانی</h3><p>واحد را در سازمان و زیر واحد والد مناسب قرار دهید.</p></div></div>
<form method="post" action="/admin/organization-setup" class="admin-form-stack admin-form-grid"><input type="hidden" name="_token" value="<?=$token?>"><input type="hidden" name="action" value="create_unit">
<label>سازمان<select name="organization_reference" required><option value="">انتخاب سازمان</option><?php foreach($workspace['organizations'] as $o):?><option value="<?=admin_h($o['public_reference'])?>"><?=admin_h($o['display_path']??$o['title'])?></option><?php endforeach;?></select></label><label>واحد بالادست<select name="parent_reference"><option value="">بدون بالادست</option><?php foreach($workspace['units'] as $u):?><option value="<?=admin_h($u['public_reference'])?>"><?=admin_h($u['display_path']??($u['organization_title'].' ← '.str_repeat('— ',(int)$u['depth']).$u['title']))?></option><?php endforeach;?></select></label>
<label>عنوان فارسی<input name="title_fa" required maxlength="255"></label><label>عنوان انگلیسی<input name="title_en" dir="ltr" maxlength="255"></label><label>کد واحد<input name="code" dir="ltr" maxlength="100"></label><label>ترتیب<input type="number" name="sort_order" min="0" value="0"></label><label class="admin-form-span">توضیحات<textarea name="description" rows="3" maxlength="2000"></textarea></label><div class="admin-form-actions"><button class="admin-button">ثبت واحد</button></div></form></div>

<div class="admin-setup-panel" data-panel="position" role="tabpanel">
<div class="admin-panel-heading"><div><h3>تعریف پست سازمانی</h3><p>پست را در سطح ستاد سازمان یا یک واحد مشخص تعریف کنید.</p></div></div>
<form method="post" action="/admin/organization-setup" class="admin-form-stack admin-form-grid"><input type="hidden" name="_token" value="<?=$token?>"><input type="hidden" name="action" value="create_position">
<label>سازمان<select name="organization_reference" required><option value="">انتخاب سازمان</option><?php foreach($workspace['organizations'] as $o):?><option value="<?=admin_h($o['public_reference'])?>"><?=admin_h($o['display_path']??$o['title'])?></option><?php endforeach;?></select></label><label>واحد<select name="unit_reference"><option value="">ستاد سازمان</option><?php foreach($workspace['units'] as $u):?><option value="<?=admin_h($u['public_reference'])?>"><?=admin_h($u['display_path']??($u['organization_title'].' ← '.$u['title']))?></option><?php endforeach;?></select></label>
<label>عنوان فارسی<input name="title_fa" required maxlength="255"></label><label>عنوان انگلیسی<input name="title_en" dir="ltr" maxlength="255"></label><label>کد پست<input name="code" dir="ltr" maxlength="100"></label><label>ظرفیت تصدی<input type="number" name="headcount_limit" min="1" value="1"></label><label>ترتیب<input type="number" name="sort_order" min="0" value="0"></label><label class="admin-inline-check"><input type="checkbox" name="is_head" value="1"><span>مسئول واحد</span></label><div class="admin-form-actions"><button class="admin-button">تعریف پست</button></div></form></div>

<div class="admin-setup-panel" data-panel="identity" role="tabpanel">
<div class="admin-panel-heading"><div><h3>اتصال کاربر به شخص</h3><p>هویت ورود را به رکورد شخص حقیقی متصل کنید.</p></div></div>
<form method="post" action="/admin/organization-setup" class="admin-form-stack admin-form-grid"><input type="hidden" name="_token" value="<?=$token?>"><input type="hidden" name="action" value="link_user_person">
<label>حساب کاربری<select name="user_id" required><option value="">انتخاب کاربر</option><?php foreach($workspace['users'] as $u):?><option value="<?=admin_h($u['id'])?>"><?=admin_h(($u['username']?:$u['email']?:$u['mobile']?:('کاربر '.$u['id'])).($u['person_name']?' ← '.$u['person_name']:''))?></option><?php endforeach;?></select></label><label>شخص<select name="person_reference" required><option value="">انتخاب شخص</option><?php foreach($workspace['persons'] as $p):?><option value="<?=admin_h($p['public_reference'])?>"><?=admin_h($p['title'].($p['national_code']?' — '.$p['national_code']:''))?></option><?php endforeach;?></select></label><div class="admin-form-actions"><button class="admin-button">ثبت اتصال</button></div></form>
<div class="admin-note">هر شخص فقط به یک حساب کاربری متصل می‌شود. اتصال مجدد همان کاربر، رابطه قبلی او را جایگزین می‌کند.</div></div>

<div class="admin-setup-panel" data-panel="summary" role="tabpanel">
<div class="admin-panel-heading"><div><h3>خلاصه و اقدامات بعدی</h3><p>وضعیت داده‌های پایه را بررسی و سپس انتصاب‌ها را ثبت کنید.</p></div></div>
<div class="admin-setup-summary"><span><b><?=count($workspace['organizations'])?></b> سازمان</span><span><b><?=count($workspace['units'])?></b> واحد</span><span><b><?=count($workspace['organization_positions'])?></b> پست سازمانی</span><span><b><?=count(array_filter($workspace['users'],fn($u)=>!empty($u['person_id'])))?></b> کاربر متصل</span></div><div class="admin-actions-row"><a class="admin-button" href="/admin/appointments">ادامه: ثبت انتصاب</a><a class="admin-button admin-button--soft" href="/admin/organization-chart">مشاهده چارت</a></div></div>
</section>
<?php endif;?>
<style>
.admin-setup-tabs{display:flex;gap:8px;overflow-x:auto;padding:4px 0 14px;border-bottom:1px solid var(--admin-border,#dbe7e1);scrollbar-width:thin}.admin-setup-tab{border:1px solid var(--admin-border,#dbe7e1);background:var(--admin-surface-soft,#f7fbf9);border-radius:10px;padding:10px 14px;white-space:nowrap;cursor:pointer;color:inherit}.admin-setup-tab.is-active{background:var(--admin-primary,#16806f);border-color:var(--admin-primary,#16806f);color:#fff}.admin-setup-panel{display:none;padding-top:18px}.admin-setup-panel.is-active{display:block}.admin-panel-heading{display:flex;justify-content:space-between;gap:12px;margin-bottom:16px}.admin-panel-heading h3{margin:0 0 5px}.admin-panel-heading p{margin:0;opacity:.72}.admin-form-stack{display:flex;flex-direction:column;gap:12px}.admin-form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.admin-form-grid label{display:flex;flex-direction:column;gap:6px}.admin-form-span,.admin-form-actions{grid-column:1/-1}.admin-form-actions{display:flex;justify-content:flex-start}.admin-inline-check{flex-direction:row!important;align-items:center;align-self:end;min-height:44px;gap:8px!important}.admin-inline-check input{width:auto}.admin-note{margin-top:14px;font-size:.88rem;opacity:.75}.admin-setup-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.admin-setup-summary span{border:1px solid var(--admin-border,#ddd);border-radius:12px;padding:14px;text-align:center}.admin-setup-summary b{display:block;font-size:1.35rem}.admin-actions-row{display:flex;gap:10px;margin-top:16px}.admin-alert--danger{background:#fff2f2!important;border-color:#efb7b7!important;color:#9f2727!important}.admin-alert--success{background:#edf9f1!important;border-color:#a9ddba!important;color:#176b39!important}
@media(max-width:760px){.admin-form-grid{grid-template-columns:1fr}.admin-form-span,.admin-form-actions{grid-column:auto}.admin-setup-summary{grid-template-columns:repeat(2,1fr)}}@media(max-width:520px){.admin-setup-tabs{display:grid;grid-template-columns:1fr 1fr;overflow:visible}.admin-setup-tab:last-child{grid-column:1/-1}.admin-setup-summary{grid-template-columns:1fr}.admin-actions-row{flex-direction:column}}
</style>
<script>(function(){const root=document.querySelector('.admin-tab-workspace');if(!root)return;const buttons=[...root.querySelectorAll('[data-tab]')],panels=[...root.querySelectorAll('[data-panel]')];function activate(name){buttons.forEach(b=>{const on=b.dataset.tab===name;b.classList.toggle('is-active',on);b.setAttribute('aria-selected',on?'true':'false')});panels.forEach(p=>p.classList.toggle('is-active',p.dataset.panel===name));try{history.replaceState(null,'','#'+name)}catch(e){}}const hash=location.hash.replace('#','');const start=buttons.some(b=>b.dataset.tab===hash)?hash:(root.dataset.activeTab||'organization');buttons.forEach(b=>b.addEventListener('click',()=>activate(b.dataset.tab)));activate(start)})();</script>
<?php $content=ob_get_clean();require __DIR__.'/layout.php';
