<?php
if (!function_exists('admin_h')) { function admin_h($v): string { return htmlspecialchars((string)($v??''), ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8',false); } }
$appointments=$appointments??[];$current=$current??null;$message=$_SESSION['admin_flash_message']??null;$error=$_SESSION['admin_flash_error']??null;unset($_SESSION['admin_flash_message'],$_SESSION['admin_flash_error']);ob_start();?>
<nav class="admin-breadcrumb"><a href="/admin/dashboard">داشبورد</a><span>/</span><a href="/admin/profile">پروفایل</a><span>/</span><span>جایگاه فعال</span></nav>
<section class="admin-module-hub admin-module-hub--teal"><div><h2>جایگاه سازمانی فعال</h2><p>این جایگاه به‌عنوان هویت سازمانی شما در اتوماسیون استفاده می‌شود.</p></div></section>
<?php if($message):?><div class="admin-alert admin-alert--success"><?=admin_h($message)?></div><?php endif;?><?php if($error):?><div class="admin-alert"><?=admin_h($error)?></div><?php endif;?>
<section class="admin-section"><?php if(!$appointments):?><div class="admin-empty-state">هیچ انتصاب فعال و معتبر برای حساب شما یافت نشد.</div><?php else:?><div class="admin-context-cards"><?php foreach($appointments as $a):$active=$current && $current['appointment_reference']===$a['appointment_reference'];?><article class="admin-user-card <?= $active?'admin-context-card--active':'' ?>"><header><div><strong><?=admin_h($a['position_title_fa'])?></strong><small><?=admin_h($a['organization_title_fa'])?></small></div><?php if($active):?><span class="admin-status-badge admin-status-badge--active">فعال</span><?php endif;?></header><p><?=admin_h($a['org_unit_title_fa']?:'ستاد مرکزی')?></p><form method="post" action="/admin/profile/organizational-context"><input type="hidden" name="_token" value="<?=admin_h((new \IPKF\Security\Csrf())->token())?>"><input type="hidden" name="appointment_reference" value="<?=admin_h($a['appointment_reference'])?>"><button class="admin-button <?= $active?'admin-button--soft':'' ?>" type="submit" <?= $active?'disabled':'' ?>><?= $active?'جایگاه فعال':'انتخاب این جایگاه' ?></button></form></article><?php endforeach;?></div><?php endif;?></section>
<style>.admin-context-cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:14px}.admin-context-card--active{outline:2px solid var(--admin-accent,#087)}</style>
<?php $content=ob_get_clean();require __DIR__.'/layout.php';
