<?php

declare(strict_types=1);
$page=is_array($page??null)?$page:[];$project=is_array($page['project']??null)?$page['project']:[];$affiliation=is_array($page['context']??null)?$page['context']:[];
$organizations=is_array($affiliation['organizations']??null)?array_values($affiliation['organizations']):[];$positions=is_array($affiliation['positions']??null)?array_values($affiliation['positions']):[];$pending=is_array($affiliation['pending']??null)?array_values($affiliation['pending']):[];$identityReady=!empty($affiliation['identity_ready']);
$csrf=(new \IPKF\Security\Csrf())->token();$text=static fn(string $key):string=>\App\Services\UiContent\UiContentInlineGuide::bodyText($key,'ticketing','membership');ob_start();
?>
<div class="admin-section"><h2><?=admin_h($text('ticketing.membership.affiliation.heading'))?></h2><p class="admin-muted"><?=admin_h($text('ticketing.membership.affiliation.project_prefix'))?> «<?=admin_h($project['title']??'')?>»</p>
<?php if(!$identityReady):?><div class="admin-alert admin-alert--danger"><?=admin_h($text('ticketing.membership.affiliation.identity_required'))?></div><a class="admin-button" href="/admin/profile"><?=admin_h($text('ticketing.membership.affiliation.identity_action'))?></a>
<?php elseif($pending!==[]):?><div class="admin-alert admin-alert--info"><?=admin_h($text('ticketing.membership.affiliation.pending'))?></div><a class="admin-button admin-button--soft" href="/admin/support/ticketing/membership"><?=admin_h($text('ticketing.membership.common.back'))?></a>
<?php elseif($organizations===[]):?><div class="admin-alert admin-alert--danger"><?=admin_h($text('ticketing.membership.affiliation.no_organization'))?></div>
<?php else:?><form method="post" action="/admin/support/ticketing/affiliation"><input type="hidden" name="_token" value="<?=admin_h($csrf)?>"><input type="hidden" name="project_reference" value="<?=admin_h($project['public_reference']??'')?>"><label><span><?=admin_h($text('ticketing.membership.affiliation.organization_label'))?></span><select name="organization_reference" id="ticketing-affiliation-organization" required><option value=""><?=admin_h($text('ticketing.membership.affiliation.organization_placeholder'))?></option><?php foreach($organizations as $organization):?><option value="<?=admin_h($organization['public_reference']??'')?>"><?=admin_h($organization['title']??'')?></option><?php endforeach;?></select></label><label><span><?=admin_h($text('ticketing.membership.affiliation.position_label'))?></span><select name="position_reference" id="ticketing-affiliation-position"><option value=""><?=admin_h($text('ticketing.membership.affiliation.position_none'))?></option><?php foreach($positions as $position):?><option value="<?=admin_h($position['public_reference']??'')?>" data-organization-reference="<?=admin_h($position['organization_reference']??'')?>" hidden><?=admin_h(trim(((($position['unit_title']??'')!=='')?(($position['unit_title']??'').' / '):'').($position['title']??'')))?></option><?php endforeach;?></select></label><label><input type="checkbox" name="is_primary" value="1"> <?=admin_h($text('ticketing.membership.affiliation.primary_label'))?></label><button type="submit" class="admin-button"><?=admin_h($text('ticketing.membership.affiliation.submit'))?></button></form><?php endif;?></div>
<script>(()=>{const o=document.getElementById('ticketing-affiliation-organization'),p=document.getElementById('ticketing-affiliation-position');if(!o||!p)return;const sync=()=>{const s=o.value||'';Array.from(p.options).forEach((x,i)=>{if(i===0){x.hidden=false;return;}x.hidden=x.dataset.organizationReference!==s;});p.value='';};o.addEventListener('change',sync);sync();})();</script>
<?php $content=ob_get_clean();require __DIR__.'/layout.php';
