<?php

namespace IPKF\Support;

class Version
{
    /*
     * Emergency fallback only.
     * Normal deployments use runtime-build.json,
     * generated by the platform deployment gate.
     */
    public const CURRENT =
        '0.0.0-dev';


    public static function current(): string
    {
        $override =
            trim(
                (string) getenv(
                    'IPKF_APP_VERSION'
                )
            );

        if (
            $override !== ''
            && self::isValid($override)
        ) {
            return $override;
        }


        $metadataPath =
            dirname(__DIR__, 2)
            . '/storage/runtime-build.json';

        if (is_file($metadataPath)) {

            $raw =
                @file_get_contents(
                    $metadataPath
                );

            if (is_string($raw)) {

                $metadata =
                    json_decode(
                        $raw,
                        true
                    );

                $version =
                    trim(
                        (string) (
                            $metadata['version']
                            ?? ''
                        )
                    );

                if (
                    $version !== ''
                    && self::isValid($version)
                ) {
                    return $version;
                }
            }
        }


        return self::CURRENT;
    }


    private static function isValid(
        string $version
    ): bool {
        return preg_match(
            '/^[0-9]+\.[0-9]+\.[0-9]+'
            . '(?:[-+][A-Za-z0-9.-]+)?$/',
            $version
        ) === 1;
    }
}
