<?php

declare(strict_types=1);
namespace IPKF\Database\Migrations;
final class CreateTicketingRequesterMembershipApprovalFoundation extends Migration
{
    public function up(): void
    {
        $this->db->exec("\n            CREATE TABLE IF NOT EXISTS ticketing_support_project_membership_requests (\n                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n                public_reference VARCHAR(50) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,\n                project_id BIGINT UNSIGNED NOT NULL,\n                user_reference VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,\n                core_organization_membership_reference VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,\n                organization_reference_snapshot VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,\n                organization_title_snapshot VARCHAR(255) NOT NULL,\n                organization_role_code_snapshot VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NULL,\n                status_code VARCHAR(30) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'pending',\n                pending_lock_key VARCHAR(220) CHARACTER SET ascii COLLATE ascii_bin NULL,\n                source_code VARCHAR(30) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'open',\n                source_reference VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NULL,\n                requested_by_user_reference VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NULL,\n                decided_by_user_reference VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NULL,\n                decision_note VARCHAR(500) NULL,\n                requested_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,\n                decided_at DATETIME NULL,\n                created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,\n                updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n                PRIMARY KEY (id),\n                UNIQUE KEY ticketing_membership_requests_ref_unique (public_reference),\n                UNIQUE KEY ticketing_membership_requests_pending_lock_unique (pending_lock_key),\n                KEY ticketing_membership_requests_project_user_status_index (project_id, user_reference, status_code),\n                KEY ticketing_membership_requests_project_status_index (project_id, status_code, requested_at),\n                KEY ticketing_membership_requests_org_status_index (organization_reference_snapshot, status_code),\n                CONSTRAINT ticketing_membership_requests_project_fk FOREIGN KEY (project_id) REFERENCES ticketing_support_projects(id) ON DELETE RESTRICT ON UPDATE RESTRICT\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci\n        ");
    }
    public function down(): void { /* audit data: non-destructive */ }
}
